package com.trading;

public enum AllocationStatus {
    ACCEPTED,
    BLOCK_LEVEL_REJECT,
    ACCOUNT_LEVEL_REJECT,
    RECEIVED,
    INCOMPLETE,
    REJECTED_BY_INTERMEDIARY,
    ALLOCATION_PENDING,
    REVERSED,
    CANCELLED_BY_INTERMEDIARY,
    CLAIMED,
    REFUSED,
    PENDING_GIVEUP_APPROVAL,
    CANCELLED,
    PENDING_TAKEUP_APPROVAL,
    REVERSAL_PENDING
}
